#
#Tue Oct 06 10:51:41 COT 2026
goog\:chromeOptions={args\=[remote-allow-origins\=*, --headless\=chrome, \\n    --headless\=new, \\n    --disable-gpu, \\n    --window-size\=1440,1000, \\n    --no-sandbox, \\n    --disable-dev-shm-usage, \\n    --remote-allow-origins\=*\\n, --headless], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
